# Location of top-level MicroPython directory
MPY_DIR = ../../micropython

# Name of module
MOD = raw_screen

# Source files (.c or .py)
SRC = raw_screen.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin, rv32imc)
ARCH = armv6m

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk